name: Release (cargo-dist)

on:
  push:
    tags:
      - "v*"
      - "vmic-v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  dist:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.90
        with:
          targets: x86_64-unknown-linux-musl

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Set up sccache
        uses: Mozilla-Actions/sccache-action@v0.0.9

      - name: Install system dependencies (musl)
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install cargo-dist
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@0.30.0

      - name: Build release artifacts with cargo-dist
        run: |
          dist build \
            --artifacts=local \
            --tag "${GITHUB_REF_NAME}" \
            --target x86_64-unknown-linux-musl

      - name: Show artifacts
        run: ls -lah target/distrib

      - name: Ensure GitHub Release exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if ! gh release view "${GITHUB_REF_NAME}" >/dev/null 2>&1; then
            gh release create "${GITHUB_REF_NAME}" \
              --title "${GITHUB_REF_NAME}" \
              --notes "Automated release."
          fi
        # gh release create/view см. мануал :contentReference[oaicite:9]{index=9}

      - name: Upload artifacts to GitHub Release (from dist manifest)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # Получаем список корректных файлов из манифеста
          dist manifest --artifacts=local --tag "${GITHUB_REF_NAME}" --output-format=json \
            | jq -r '.upload_files[]' \
            | while IFS= read -r path; do
                # upload_files уже исключает мусорные файлы (например, timestamp), см. schema
                if [ -f "$path" ]; then
                  gh release upload "${GITHUB_REF_NAME}" "$path" --clobber
                fi
              done
