name: Release (cargo-dist)

on:
  push:
    tags:
      - "v*"
      - "vmic-v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install system dependencies (musl)
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install cargo-dist
        run: cargo install cargo-dist --locked --version 0.30.0

      - name: Build release artifacts with cargo-dist
        run: dist build --tag "${GITHUB_REF_NAME}" --target x86_64-unknown-linux-musl

      - name: Show artifacts
        run: ls -lah target/dist

      - name: Ensure GitHub Release exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh release view "${GITHUB_REF_NAME}"; then
            gh release create "${GITHUB_REF_NAME}" --title "${GITHUB_REF_NAME}" --notes "Automated release."
          fi

      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${GITHUB_REF_NAME}" target/dist/* --clobber
